spring:
    cloud:
        gateway:
          routes:
              - id: question-service
                uri: lb://QUESTION-SERVICE
                predicates:
                  - Path=/question_service/**
                filters:
                  - AuthenticationFilter
                  
              - id: quiz-service
                uri: lb://QUIZ-SERVICE
                predicates:
                  - Path=/quiz/**
                filters:
                  - AuthenticationFilter

              - id: user-service
                uri: lb://USER-SERVICE
                predicates:
                  - Path=/User/**
                filters:
                  - AuthenticationFilter
                
              - id: quiz-streamer-service
                uri: lb://QUIZ-STREAMER-SERVICE
                predicates:
                  - Path=/quizstreamer/**
                filters:
                  - AuthenticationFilter
server:
    port: 8222

management:
  endpoints:
    web:
      exposure:
        include: "*"
