spring:
  datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.3:5432/auth_db
        username: salman
        password: salman
  jpa:
        open-in-view: false
        database-platform:  org.hibernate.dialect.PostgreSQLDialect
        hibernate:            
            ddl-auto: update
server:
  port: 8086