spring:
    servlet:
        multipart: 
            enabled: true
            max-file-size: 10MB
            max-request-size: 12MB
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.3:5432/file_manager_db
        username: salman
        password: salman
    jpa:
        
        hibernate:            
            ddl-auto: update
    properties:
        hibernate: 
            dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8087